# Generated by Django 4.0.1 on 2022-01-25 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HOME', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sliderimages',
            options={'verbose_name_plural': 'Slider Images'},
        ),
    ]
